// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201019193825_SeedActivitiesTable")]
    partial class SeedActivitiesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc3b6df6-0118-4e44-b6f5-82f7645c74f7"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2020, 8, 19, 14, 38, 25, 584, DateTimeKind.Local).AddTicks(3010),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("411e04c4-2ba1-40d8-be01-a656319634e7"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2020, 9, 19, 14, 38, 25, 597, DateTimeKind.Local).AddTicks(2190),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("1525ffc8-c893-441b-9f08-a7760b061698"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2020, 11, 19, 14, 38, 25, 597, DateTimeKind.Local).AddTicks(2270),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("6e7763f4-f677-4cde-aa8e-4a6a8c9c62a1"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2020, 12, 19, 14, 38, 25, 597, DateTimeKind.Local).AddTicks(2270),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("c3481f1a-f70b-438c-a78f-45a4da2d5248"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2021, 1, 19, 14, 38, 25, 597, DateTimeKind.Local).AddTicks(2280),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("144645da-c088-4282-80f2-184c5070bd2f"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2021, 2, 19, 14, 38, 25, 597, DateTimeKind.Local).AddTicks(2290),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("bc4d1f45-d670-4682-ae42-63055e5d50b9"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2021, 3, 19, 14, 38, 25, 597, DateTimeKind.Local).AddTicks(2290),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("deb2e4b4-9eea-4525-823a-9e82080c97ce"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2021, 4, 19, 14, 38, 25, 597, DateTimeKind.Local).AddTicks(2300),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("9f0625c6-f7c3-4b81-a06c-f0998d549cde"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2021, 5, 19, 14, 38, 25, 597, DateTimeKind.Local).AddTicks(2300),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("a8b5b714-6cee-4189-ac2b-c3b7c02f6c9e"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2021, 6, 19, 14, 38, 25, 597, DateTimeKind.Local).AddTicks(2310),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Value 101"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Value 102"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Value 103"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
